apiVersion: v1
kind: ServiceAccount
metadata:
  name: zynk-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zynk-lease-role
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "create", "update", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zynk-lease-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zynk-lease-role
subjects:
  - kind: ServiceAccount
    name: zynk-sa