apiVersion: v1
kind: Service
metadata:
  name: zynkd-headless
  labels:
    app: zynkd
spec:
  clusterIP: None
  selector:
    app: zynkd
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051